export const QK = {
  PEOPLES: "PEOPLES",
  POST: "POST",
  POSTS: "POSTS",
  BOOKMARKS: "BOOKMARKS",
  NOTIFICATIONS: "NOTIFICATIONS",
  CONNECTIONS: "CONNECTIONS",
  PROFILE: "PROFILE",
  CAUSES: "CAUSES",
  NEIGHBORHOOD: "NEIGHBORHOOD",
  CONVERSATION: "CONVERSATION",
  COMMENTS: "COMMENTS",
  MESSAGES: "MESSAGES",
};
