import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./../globals.css";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative">
          <NavBar />
          <main className="mt-[80px]">
            <div className="grid grid-cols-12 gap-x-8 mb-8 px-12">
              {children}
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
